

image:
  file: .gitpod.dockerfile

tasks:
  - name: Install dependencies
    command: pip install -r requirements.txt

  - name: Start the server
    command: python3 server.py

ports:
  - port: 5000
    onOpen: open-preview